/**
 * Created by pankajjakhar on 11/09/21.
 */

public with sharing class QueueConfigurationConstants {
    public static final String EVENT_TYPE_AC = 'AC';
    public static final String EVENT_TYPE_ACC = 'ACC';
    public static final String EVENT_TYPE_ACOC = 'ACOC';

    public static final String QUEUE_NAME_ACCOUNT_Q = 'AccountQ';
    public static final String QUEUE_NAME_CONTACT_Q = 'ContactQ';
    public static final String QUEUE_NAME_CASE_Q = 'CaseQ';
}